# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidacion', '0002_visita_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='edad',
            field=models.CharField(blank=True, max_length=50, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='visita',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('V', 'Viudo'), ('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divorciado')], max_length=1, verbose_name='estado civil'),
        ),
    ]
