# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('fecha_inicio',)},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name_plural': 'Salones'},
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(help_text='Grupo al que asiste el estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='grupos.Grupo', verbose_name='Grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together=set([('materia', 'prioridad')]),
        ),
        migrations.AlterUniqueTogether(
            name='sesion',
            unique_together=set([('modulo', 'prioridad')]),
        ),
    ]
