# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 08:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituto', '0002_auto_20171122_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='color',
            field=models.CharField(default='bgm-pink', max_length=100, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='dia',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sabado'), ('6', 'Domingo')], max_length=1, verbose_name='Día'), size=None),
        ),
    ]
