# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_auto_20170921_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalafon',
            options={'verbose_name_plural': 'Escalafones'},
        ),
        migrations.AlterModelOptions(
            name='miembro',
            options={'permissions': (('es_agente', 'define si un miembro es agente'), ('es_lider', 'indica si el usuario es lider de un GAR'), ('es_administrador', 'es adminisitrador'), ('es_pastor', 'indica si un miembro es pastor'), ('es_tesorero', 'indica si un miembro es tesorero'), ('es_coordinador', 'indica si un miembro es coordinador'), ('es_maestro', 'indica si un miembro es maestro'), ('buscar_todos', 'indica si un usuario puede buscar miembros'))},
        ),
    ]
