# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 14:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20170405_1756'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='grupo',
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
