# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20171122_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniondiscipulado',
            name='numeroLideresAsistentes',
        ),
    ]
