# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 11:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_remove_reuniondiscipulado_numerolideresasistentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTree',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('grupos.grupo',),
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
